language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "bxSK2HvFuFrvddjlz9NCfbxGFKYmZQ++AlB3dduDCFH3wjFttb49PtCXReu2wvODWCRUi2pzGC1ouf0y44lxTJ/cZYBAegic9gbk0Ud2djFiHLMRsMUL3sZdCtqfgbezdQahJyqZmEjwvbrNVW0JB0EK6cDZgf+0kW8/b5igdgdVqVq6O/A1BmF7XBC3FSPXv1SU6ArYLfcvglHDPCEjgtqn/BcTfcqxCO/RKSv1Yymn3VNNDCZbwC+zZWPGbuRcdoYYQXMDt/1A5RSQGWcQLGGN1PXkJbLyqeG1fmhJtoo9XPaA6SbpL7DpzdYLPhakGRoNJJzII0mydUAySHTJ2klkMxpcq41rSPsSl/M8FuUInV830t/unXJIhaFaxZhuK/qefGITPf7k+THx3aQpqO9R+J5Gt/GP2B4zEoQjmT8MCs4LT7vkuhEOaHs5HYKDYasFB9Y0WxQIOzVoX4w9WHnMvAMHI3a3QKMTdbVdstc40dcQaTmv97RCObKjHqdlK2KoZAWTVIRQQfQFaqtTggm7tQ++/GtgJtWcPSx+RA67SqXM8losZHTph2N4qaiSfwnl9jmlFgGOuj7VXNGTfd0epvcqxw0Fd6E6dodehVyoKD3h2RKLGaJ36Su7vlKwkYTNDpVRZuzwV4DFcdHN9KR+UA3/6HwHRg9Bt3k6ITs="